<a href="https://colab.research.google.com/github/thevaibhavpal6/campusx/blob/main/numpy_end.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,100,15)

In [3]:
a

array([88, 84, 43, 50, 70, 68, 65,  8, 63, 43, 71, 79, 40, 31, 84])

In [5]:
np.sort(a).reshape(3,5)

array([[ 8, 31, 40, 43, 43],
       [50, 63, 65, 68, 70],
       [71, 79, 84, 84, 88]])

In [6]:
b=np.random.randint(1,100,25)

In [10]:
c=b.reshape(5,5)

In [11]:
np.sort(c,axis=0)

array([[ 8, 39, 30,  9, 50],
       [36, 42, 62, 33, 52],
       [51, 54, 66, 84, 55],
       [72, 91, 83, 88, 69],
       [82, 98, 98, 99, 78]])

In [12]:
np.sort(c,axis=1)

array([[ 8,  9, 30, 69, 91],
       [39, 55, 66, 72, 88],
       [36, 54, 78, 98, 99],
       [33, 50, 62, 82, 98],
       [42, 51, 52, 83, 84]])

In [13]:
c

array([[ 8, 91, 30,  9, 69],
       [72, 39, 66, 88, 55],
       [36, 54, 98, 99, 78],
       [82, 98, 62, 33, 50],
       [51, 42, 83, 84, 52]])

In [16]:
np.append(c,np.random.random((c.shape[1],1)),axis=1)

array([[ 8.        , 91.        , 30.        ,  9.        , 69.        ,
         0.41754163],
       [72.        , 39.        , 66.        , 88.        , 55.        ,
         0.11327095],
       [36.        , 54.        , 98.        , 99.        , 78.        ,
         0.1409629 ],
       [82.        , 98.        , 62.        , 33.        , 50.        ,
         0.92643104],
       [51.        , 42.        , 83.        , 84.        , 52.        ,
         0.57708968]])

In [17]:
d=np.random.randint(1,100,25)

In [18]:
np.where(a>50)

(array([ 0,  1,  4,  5,  6,  8, 10, 11, 14]),)

In [22]:
np.where(a>50,0,a)

array([ 0,  0, 43, 50,  0,  0,  0,  8,  0, 43,  0,  0, 40, 31,  0])

In [23]:
np.where(a%2 == 0,0,1)

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0])

In [25]:
np.argmax(c,axis=0)

array([3, 3, 2, 2, 2])

In [26]:
np.argmax(c,axis=1)

array([1, 3, 3, 1, 3])

In [27]:
u=np.random.randint(1,100,30)

In [30]:
np.clip(u,a_min=30,a_max=80)

array([38, 80, 73, 39, 31, 34, 30, 80, 43, 80, 30, 30, 80, 80, 30, 80, 71,
       30, 80, 30, 32, 80, 30, 30, 32, 34, 46, 37, 70, 73])