<a href="https://colab.research.google.com/github/thevaibhavpal6/campusx/blob/main/pandasi_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [ ]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.random.random((3,4))

array([[0.57732422, 0.61715529, 0.71248408, 0.91699497],
       [0.93146615, 0.72385747, 0.2922076 , 0.53232677],
       [0.14408667, 0.92330004, 0.08902653, 0.760256  ]])

In [ ]:
np.linspace(-10,17,20,dtype=int)

array([-10,  -9,  -8,  -6,  -5,  -3,  -2,  -1,   1,   2,   4,   5,   7,
         8,   9,  11,  12,  14,  15,  17])

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
a1=np.arange(10,dtype=np.int32)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
a2= np.arange(12,dtype=float).reshape(3,4)

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a3=np.arange(8).reshape(2,2,2)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a2.ndim

2

In [ ]:
print(a3.shape)

(2, 2, 2)


In [ ]:
a2=np.arange(12,24).reshape(3,4)

In [ ]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a2**2

array([[144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [ ]:
a2 == 13

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [37]:
h1= np.random.random((3,4))

In [38]:
h1

array([[0.40125982, 0.35733509, 0.54371775, 0.22623803],
       [0.17192471, 0.54494687, 0.12111813, 0.28696806],
       [0.15192245, 0.47173847, 0.56236195, 0.75110685]])

In [39]:
h1=np.round((h1*100))

In [40]:
h1

array([[40., 36., 54., 23.],
       [17., 54., 12., 29.],
       [15., 47., 56., 75.]])

In [41]:
np.prod(h1,axis=0)

array([10200., 91368., 36288., 50025.])

In [42]:
np.prod(h1,axis=1)

array([1788480.,  319464., 2961000.])

In [45]:
 for i in h1:
  i=i*2
  print(i)

[ 80.  72. 108.  46.]
[ 34. 108.  24.  58.]
[ 30.  94. 112. 150.]


In [46]:
np.transpose(h1)

array([[40., 17., 15.],
       [36., 54., 47.],
       [54., 12., 56.],
       [23., 29., 75.]])

In [47]:
h1.T

array([[40., 17., 15.],
       [36., 54., 47.],
       [54., 12., 56.],
       [23., 29., 75.]])

In [48]:
h1.ravel()

array([40., 36., 54., 23., 17., 54., 12., 29., 15., 47., 56., 75.])

In [49]:
a4=np.arange(12).reshape(3,4)

In [50]:
a5=np.arange(12,24).reshape(3,4)

In [53]:
q=np.hstack((a4,a5))

In [54]:
q

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [55]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
a= [i for i in range(1000000)]
b= [i for i in range(1000000,2000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time() - start)

0.1655130386352539


In [58]:
y=np.arange(24).reshape(6,4)

In [59]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
y[2,2]

np.int64(10)

In [61]:
y[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [62]:
y[:,[2,3]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [63]:
a=np.random.randint(1,100,24).reshape(6,4)

In [64]:
a

array([[21, 41, 25, 35],
       [71,  9, 13, 57],
       [49, 12,  2,  7],
       [93, 14, 70, 13],
       [49, 35,  2,  6],
       [72, 54, 32, 22]])

In [65]:
a[a>50]

array([71, 57, 93, 70, 72, 54])

In [67]:
a[(a>50) & (a%2 ==0)]

array([70, 72, 54])